# Generated by Django 3.2.2 on 2021-05-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0002_alter_student_yearofgraduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='type',
            field=models.CharField(max_length=2),
        ),
    ]
